force-app/main/default/objects/Trade__c/Trade__c.object-meta.xml
<CustomObject>
    <label>Trade</label>
    <nameField>
        <displayFormat>TR{0000000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Trades</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Trade__c/fields/Buy_Amount__c.field-meta.xml
<CustomField>
    <fullName>Buy_Amount__c</fullName>
    <label>Buy Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Trade__c/fields/Buy_Currency__c.field-meta.xml
<CustomField>
    <fullName>Buy_Currency__c</fullName>
    <label>Buy Currency</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Currencies_ISO_Code</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Trade__c/fields/Date_Booked__c.field-meta.xml
<CustomField>
    <fullName>Date_Booked__c</fullName>
    <label>Date Booked</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Trade__c/fields/Rate__c.field-meta.xml
<CustomField>
    <fullName>Rate__c</fullName>
    <label>Rate</label>
    <precision>18</precision>
    <required>true</required>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Trade__c/fields/Sell_Currency__c.field-meta.xml
<CustomField>
    <fullName>Sell_Currency__c</fullName>
    <label>Sell Currency</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Currencies_ISO_Code</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Currencies_ISO_Code.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>AFN</fullName>
    </customValue>
    <customValue>
        <fullName>ALL</fullName>
    </customValue>
    <customValue>
        <fullName>AMD</fullName>
    </customValue>
    <customValue>
        <fullName>ANG</fullName>
    </customValue>
    <customValue>
        <fullName>AOA</fullName>
    </customValue>
    <customValue>
        <fullName>ARS</fullName>
    </customValue>
    <customValue>
        <fullName>AUD</fullName>
    </customValue>
    <customValue>
        <fullName>AWG</fullName>
    </customValue>
    <customValue>
        <fullName>AZN</fullName>
    </customValue>
    <customValue>
        <fullName>BAM</fullName>
    </customValue>
    <customValue>
        <fullName>BBD</fullName>
    </customValue>
    <customValue>
        <fullName>BDT</fullName>
    </customValue>
    <customValue>
        <fullName>BGN</fullName>
    </customValue>
    <customValue>
        <fullName>BHD</fullName>
    </customValue>
    <customValue>
        <fullName>BIF</fullName>
    </customValue>
    <customValue>
        <fullName>BMD</fullName>
    </customValue>
    <customValue>
        <fullName>BND</fullName>
    </customValue>
    <customValue>
        <fullName>BOB</fullName>
    </customValue>
    <customValue>
        <fullName>BOV</fullName>
    </customValue>
    <customValue>
        <fullName>BRL</fullName>
    </customValue>
    <customValue>
        <fullName>BSD</fullName>
    </customValue>
    <customValue>
        <fullName>BTN</fullName>
    </customValue>
    <customValue>
        <fullName>BWP</fullName>
    </customValue>
    <customValue>
        <fullName>BYN</fullName>
    </customValue>
    <customValue>
        <fullName>BZD</fullName>
    </customValue>
    <customValue>
        <fullName>CAD</fullName>
    </customValue>
    <customValue>
        <fullName>CDF</fullName>
    </customValue>
    <customValue>
        <fullName>CHF</fullName>
    </customValue>
    <customValue>
        <fullName>CLF</fullName>
    </customValue>
    <customValue>
        <fullName>CLP</fullName>
    </customValue>
    <masterLabel>Currencies ISO Code</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/NewTradePostBatch.cls
/*
* @author         Luca Gouvea
* @modifiedBy     Luca Gouvea 
* @maintainedBy   Luca Gouvea
* @version        1.0
* @created        2022-06-22
* @modified       2022-06-22
* Purpose: 		  this batch will create a chatter post for each member of Queue regarding new Trades 
*/

global class NewTradePostBatch implements Database.batchable<sObject>, Database.Stateful {

    global List<Trade__c> tradeSet;
    String bodyTemplate;
    
    //Constructor holds the Accounts that need to be updated
    global NewTradePostBatch(List<Trade__c> tradeSet){
        this.tradeSet = tradeSet;
        this.bodyTemplate = [SELECT Id, Body FROM StaticResource WHERE Name = 'NewTradeChatterPost' LIMIT 1].Body.toString();
    }
    
    global Database.QueryLocator start(Database.BatchableContext BC){    
        Id queueId = [SELECT Id FROM Group WHERE type = 'Queue' AND DeveloperName ='Trade_Reviewers' LIMIT 1].Id;   
        return Database.getQueryLocator([SELECT UserOrGroupId FROM GroupMember WHERE GroupId =:queueId]);       
    }
    
    //Execute will separate Accounts and respective Cases in a map and perform the calculations
    global void execute(Database.BatchableContext BC, List<GroupMember> scope){

        List<FeedItem> feedItemList = new List<FeedItem>();
        
        if(!scope.isEmpty()){      
            for(Trade__c trade : tradeSet){
                String body = buildPostBody(trade, bodyTemplate);

                for(GroupMember member : scope){
                    FeedItem post = new FeedItem();
                    post.Body = body;
                    post.ParentId = member.UserOrGroupId;
                    feedItemList.add(post);
                }
            }

            Database.insert(feedItemList, true);
        }
    }
    
    global void finish(Database.BatchableContext BC){
        
    }

    private static String buildPostBody(Trade__c trade, String bodyTemplate){
        String body = bodyTemplate.replace('%%SELL_CURRENCY%%', string.valueOf(trade.Sell_Currency__c));
        body = body.replace('%%SELL_AMOUNT%%', string.valueOf(trade.Sell_Amount__c));
        body = body.replace('%%BUY_CURRENCY%%', string.valueOf(trade.Buy_Currency__c));
        body = body.replace('%%BUY_AMOUNT%%', string.valueOf(trade.Buy_Amount__c));
        body = body.replace('%%RATE%%', string.valueOf(trade.Rate__c));
        body = body.replace('%%DATETIME%%', string.valueOf(trade.Date_Booked__c));
        body = body.replace('%%TRADE_LINK%%', URL.getSalesforceBaseUrl().toExternalForm()+'/'+trade.Id);

        return body;
    }
}