force-app/main/default/objects/Trade__c/Trade__c.object-meta.xml
<CustomObject>
    <label>Trade</label>
    <nameField>
        <displayFormat>TR{0000000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Trades</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Trade__c/fields/Buy_Amount__c.field-meta.xml
<CustomField>
    <fullName>Buy_Amount__c</fullName>
    <label>Buy Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Trade__c/fields/Buy_Currency__c.field-meta.xml
<CustomField>
    <fullName>Buy_Currency__c</fullName>
    <label>Buy Currency</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Currencies_ISO_Code</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Trade__c/fields/Date_Booked__c.field-meta.xml
<CustomField>
    <fullName>Date_Booked__c</fullName>
    <label>Date Booked</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Trade__c/fields/Rate__c.field-meta.xml
<CustomField>
    <fullName>Rate__c</fullName>
    <label>Rate</label>
    <precision>18</precision>
    <required>true</required>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Trade__c/fields/Sell_Currency__c.field-meta.xml
<CustomField>
    <fullName>Sell_Currency__c</fullName>
    <label>Sell Currency</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Currencies_ISO_Code</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Currencies_ISO_Code.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>AFN</fullName>
    </customValue>
    <customValue>
        <fullName>ALL</fullName>
    </customValue>
    <customValue>
        <fullName>AMD</fullName>
    </customValue>
    <customValue>
        <fullName>ANG</fullName>
    </customValue>
    <customValue>
        <fullName>AOA</fullName>
    </customValue>
    <customValue>
        <fullName>ARS</fullName>
    </customValue>
    <customValue>
        <fullName>AUD</fullName>
    </customValue>
    <customValue>
        <fullName>AWG</fullName>
    </customValue>
    <customValue>
        <fullName>AZN</fullName>
    </customValue>
    <customValue>
        <fullName>BAM</fullName>
    </customValue>
    <customValue>
        <fullName>BBD</fullName>
    </customValue>
    <customValue>
        <fullName>BDT</fullName>
    </customValue>
    <customValue>
        <fullName>BGN</fullName>
    </customValue>
    <customValue>
        <fullName>BHD</fullName>
    </customValue>
    <customValue>
        <fullName>BIF</fullName>
    </customValue>
    <customValue>
        <fullName>BMD</fullName>
    </customValue>
    <customValue>
        <fullName>BND</fullName>
    </customValue>
    <customValue>
        <fullName>BOB</fullName>
    </customValue>
    <customValue>
        <fullName>BOV</fullName>
    </customValue>
    <customValue>
        <fullName>BRL</fullName>
    </customValue>
    <customValue>
        <fullName>BSD</fullName>
    </customValue>
    <customValue>
        <fullName>BTN</fullName>
    </customValue>
    <customValue>
        <fullName>BWP</fullName>
    </customValue>
    <customValue>
        <fullName>BYN</fullName>
    </customValue>
    <customValue>
        <fullName>BZD</fullName>
    </customValue>
    <customValue>
        <fullName>CAD</fullName>
    </customValue>
    <customValue>
        <fullName>CDF</fullName>
    </customValue>
    <customValue>
        <fullName>CHF</fullName>
    </customValue>
    <customValue>
        <fullName>CLF</fullName>
    </customValue>
    <customValue>
        <fullName>CLP</fullName>
    </customValue>
    <masterLabel>Currencies ISO Code</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/TradeTriggerHandlerTest.cls
 @isTest
public with sharing class TradeTriggerHandlerTest {

    @TestSetup
    static void makeData(){
        PermissionSet ps = [SELECT Id FROM PermissionSet WHERE Name = 'Ebury_App'];
        User user = TestDataFactory.instantiateStandardUser(true);
        PermissionSetAssignment psa = new PermissionSetAssignment(PermissionSetId = ps.id, AssigneeId = user.Id);
        insert psa;

        Id queueId = [SELECT Id FROM Group WHERE type = 'Queue' AND DeveloperName ='Trade_Reviewers' LIMIT 1].Id;
        GroupMember gm = new GroupMember(UserOrGroupId = user.Id, GroupId = queueId);
        insert gm;
    }

    @isTest
    static void saveDateBookedTest(){
        User user = [SELECT Id FROM User WHERE Email = 'uniqueTest@anyprovider.com'];

        System.runAs(user){
            Test.startTest();
            Trade__c trade = TestDataFactory.instantiateTrade(true);
            Test.stopTest();

            Trade__c td = [SELECT Id, Date_Booked__c FROM Trade__c LIMIT 1];
            system.assert(td.Date_Booked__c != null, 'Field Date Booked saved in beforeInsert context');
        }
    }

    @isTest
    static void newChatterPostTest(){
        User user = [SELECT Id FROM User WHERE Email = 'uniqueTest@anyprovider.com'];

        System.runAs(user){
            Test.startTest();
            Trade__c trade = TestDataFactory.instantiateTrade(true);
            List<Trade__c> tradeList =[SELECT Sell_Currency__c,Buy_Currency__c,Sell_Amount__c,Buy_Amount__c,Rate__c,Date_Booked__c FROM Trade__c];
            Database.executeBatch(new NewTradePostBatch(tradeList));
            Test.stopTest();
        }
        
        List<FeedItem> fd = [SELECT Id FROM FeedItem WHERE ParentId = :user.Id];
        system.assert(fd.size() > 0, 'Chatter posts were created.');
    }

    static void newChatterPostTestFail(){
        User user = [SELECT Id FROM User WHERE Email = 'uniqueTest@anyprovider.com'];

        System.runAs(user){
            Test.startTest();
            Trade__c trade = new Trade__c();
            try {
                Database.executeBatch(new NewTradePostBatch(new List<Trade__c>{trade}));
            }catch(Exception ex){
                system.assert(true, 'Chatter posts with error.');
            }
            
            Test.stopTest();
        }
    }
}